version: '3.3'

services:  
  mongo:
    image: mongo
    container_name: mongodb
    restart: on-failure
    environment:
      MONGO_INITDB_ROOT_USERNAME: wishlist
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: wishlist
    ports:
      - 27018:27017
    networks:
      - wishlist-network

  wishlist:
    container_name: wishlist
    build:
      context: .
      dockerfile: Dockerfile
    image: wishlist
    ports:
      - "8080:8080"
      - "443:443"      
    environment:
      SPRING_PROFILES_ACTIVE: prod
    networks:
      - wishlist-network 
    depends_on:
      - mongo

networks:
  wishlist-network:
    driver: bridge
    ipam:
      driver: default
