server:
  port: 8080
  servlet:
    context-path: /wishlist-backend

spring:
  application:
    name: wishlist
  web:
    locale: pt-BR
  data:
    mongodb:
      uri: "mongodb://wishlist:pass@localhost:27018/wishlist?authSource=admin\
        &serverSelectionTimeoutMS=2000\
        &connectTimeoutMS=2000"
      auto-index-creation: true

springdoc:
  show-actuator: true
  writer-with-default-pretty-printer: true
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - url: /openapi.yml
        name: v0
